# Generated by Django 5.1.1 on 2025-01-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupon_notification_productfaq_review_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sean',
            new_name='seen',
        ),
    ]
